### ISSUE TITLE
Error: ENOENT: no such file or directory, open './frame/testapi/version.json'

### ISSUE THREAD

**Issue by bulverismo** [sroehrl/neoan3-cli#2]
hi
i am in a debian 

# neoan3 new frame testApi
writing...
/usr/lib/node_modules/neoan3-cli/actions/fileCreator.js:294
                if (err) throw err;
                         ^

Error: ENOENT: no such file or directory, open './frame/testapi/version.json'

**Comment by sroehrl** [comment]
Hi there.
I moved this issue here as this is an issue with the cli, not the framework.

Please try version 2.1.1 (just run `npm i -g neoan3-cli` again)

This is an issue with case sensitivity. In order to provide a fast fix for you, I quickly updated the cli. I will still need to run some tests to verify all occurrences are are fixed. But you should be good.
Thank you so much for reporting!

**Comment by bulverismo** [comment]
You did magic, thanks!

neoan3 new frame testApi
writing ...
Frame testApi created
